### ISSUE TITLE
Snipper Returns "Not found for URL"

### ISSUE THREAD

**Issue by GaryFurash** [mesuutt/snipper#2]
Traceback (most recent call last):
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\Scripts\snipper.exe\__main__.py", line 9, in <module>
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\snipper\snipper.py", line 343, in sync_snippets

    data = api.get_all()
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\snipper\api.py", line 30, in get_all
    res = self.get(self.config.get('snipper', 'username'))
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\snipper\api.py", line 18, in get
    res.raise_for_status()
  File "C:\Program Files\WinPython3\python-3.5.3.amd64\lib\site-packages\requests\models.py", line 893, in raise_for_sta
tus
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.bitbucket.org/2.0/snippets%5Cgary_furash

**Comment by mesuutt** [comment]
@GaryFurash I think your username in config file starts with backslash. Please check your config file and inform me if it not works.
