### ISSUE TITLE
KeyError: 'username'

### ISSUE THREAD

**Issue by edel** [mesuutt/snipper#3]
thank you for sharing this code!

i get key error when adding a snippet. 

> $ snipper new test.py 
Snippet creating...
Created snippet cloned from Bitbucket
Traceback (most recent call last):
  File "/opt/interpreters/python/3/adm/bin/snipper", line 8, in <module>
    sys.exit(cli())
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/snipper/snipper.py", line 327, in new_snippet
    print(snippet.get_detail_for_print())
  File "/opt/interpreters/python/3/adm/lib/python3.8/site-packages/snipper/snippet.py", line 97, in get_detail_for_print
    u'Owner     : {}'.format(self.data['owner']['username']),
KeyError: 'username'

apparently the json file in my `.snippets/` directory does not have `username` but `display_name` key. i changed & updated in line 97 of `snippets.py` and it seems to work fine.

**Comment by mesuutt** [comment]
related PR merged.
